apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing 
spec:
  replicas: 2
  selector:
    matchLabels:
        app: web
  template:
     metadata:
         labels:
            app: web
     spec:
       containers:
         - name: web-frontend
           image: nkunta504/jenkinscicd:tag
           ports:
            - containerport: 8000
